name: My Starter Workflow3

on:
  pull_request:
    types: [labeled]
    branches:
      - 'main'
  workflow_dispatch:

jobs:   
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage3')
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
          
  call-reusable-workflow-demo:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Testing Composite Action
        continue-on-error: true
        id: test_composite_action
        uses: octodemo/my-composite-action@main
        with:
          token: ${{ secrets.OCTODEMO_OCTODEMO_BOT_TOKEN }}
          org: octodemo
