name: My Starter Workflow2

on:
  pull_request:
    types: [labeled]
    branches:
      - 'main'
  workflow_dispatch:

jobs:   
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage2')
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
          
  call-reusable-workflow:
    if: contains(github.event.pull_request.labels.*.name, 'stage2')
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    uses: yuuki1967/callee_repo/.github/workflows/reusable-workflow.yml@v1.0.0
    with:
      node: ${{ matrix.nodeversion }}   
